# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  snap7_config = debug
endif
ifeq ($(config),release)
  snap7_config = release
endif

PROJECTS := snap7

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

snap7:
ifneq (,$(snap7_config))
	@echo "==== Building snap7 ($(snap7_config)) ===="
	@${MAKE} --no-print-directory -C build -f Makefile config=$(snap7_config)
endif

clean:
	@${MAKE} --no-print-directory -C build -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   snap7"
	@echo ""
	@echo "For more information, see http://industriousone.com/premake/quick-start"